### ISSUE TITLE
How is an empty repository a great client?

### ISSUE THREAD

**Issue by Vertex-Client** [Affannnn/Flqme-Mod-Menu#1]
xD

lol

**Comment by Affannnn** [comment]
I was too lazy to post I'll post tomorrow the client...

**Comment by Vertex-Client** [comment]
I'm pretty sure you didn't make the Flqme client though...

**Comment by Affannnn** [comment]
I didn't make but who made flqme he is my friend so i can post

**Comment by Vertex-Client** [comment]
Oh ok, but please remove the Utils part of the code since we didn't give permission to use it.

**Comment by Affannnn** [comment]
What code... This empty i did not do anything...
